-- Student-submitted honest reviews via one-time link (generated by admin/trainer).

CREATE TABLE IF NOT EXISTS "HonestReviewLink" (
  token TEXT PRIMARY KEY,
  "studentId" TEXT NOT NULL REFERENCES "Student"(id) ON DELETE CASCADE,
  "createdBy" TEXT NOT NULL REFERENCES "User"(id) ON DELETE CASCADE,
  "usedAt" TIMESTAMPTZ,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_hrl_student ON "HonestReviewLink"("studentId");

CREATE TABLE IF NOT EXISTS "StudentHonestReview" (
  id TEXT PRIMARY KEY DEFAULT gen_random_uuid()::text,
  "studentId" TEXT NOT NULL REFERENCES "Student"(id) ON DELETE CASCADE,
  "linkToken" TEXT REFERENCES "HonestReviewLink"(token) ON DELETE SET NULL,
  content TEXT NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_shr_student ON "StudentHonestReview"("studentId");
